# Generated by Django 5.1.1 on 2024-09-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_delete_taskmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
